export const FAVORITES_ADD_REQUEST = "FAVORITES_ADD_REQUEST";
export const FAVORITES_ADD_SUCCESS = "FAVORITES_ADD_SUCCESS";
export const FAVORITES_ADD_FAIL = "FAVORITES_ADD_FAIL";

export const FAVORITES_REMOVE_REQUEST = "FAVORITES_REMOVE_REQUEST";
export const FAVORITES_REMOVE_SUCCESS = "FAVORITES_REMOVE_SUCCESS";
export const FAVORITES_REMOVE_FAIL = "FAVORITES_REMOVE_FAIL";
